export type Difficulty = 'beginner' | 'intermediate' | 'advanced'
export type Category = 'foundation' | 'communication' | 'persuasion' | 'debate' | 'roleplay' | 'professional' | 'ai-special'

export interface InterviewReview {
  name: string
  text: string
  rating: number
}

export interface InterviewType {
  id: string
  slug: string
  title: string
  description: string
  category: Category
  difficulty: Difficulty
  duration: string
  rating: number
  icon: string
  tags: string[]
  whatYouPractice: string[]
  whatAIMeasures: string[]
  sampleQuestion: string
  reviews: InterviewReview[]
  prerequisites: string[]
  sessionsCompleted: number
}

export const categoryLabels: Record<Category, string> = {
  foundation: '🟢 Foundation',
  communication: '💬 Communication',
  persuasion: '🔴 Persuasion',
  debate: '🔴 Debate & Defense',
  roleplay: '🎭 Role Play',
  professional: '💼 Professional',
  'ai-special': '🤖 AI Special',
}

export const categoryColors: Record<Category, string> = {
  foundation: 'emerald',
  communication: 'sky',
  persuasion: 'rose',
  debate: 'red',
  roleplay: 'violet',
  professional: 'amber',
  'ai-special': 'cyan',
}

export const difficultyConfig: Record<Difficulty, { label: string; color: string; dot: string }> = {
  beginner: { label: 'Beginner', color: 'text-emerald-400', dot: '🟢' },
  intermediate: { label: 'Intermediate', color: 'text-yellow-400', dot: '🟡' },
  advanced: { label: 'Advanced', color: 'text-red-400', dot: '🔴' },
}

export const interviewTypes: InterviewType[] = [
  // ── FOUNDATION LEVEL ──
  { id: 'basic-interview', slug: 'basic-interview', title: 'Basic Interview', description: 'Standard question-answer format. Practice common HR questions like "Tell me about yourself", "Why should we hire you". Perfect starting point for absolute beginners.', category: 'foundation', difficulty: 'beginner', duration: '10 min', rating: 4.8, icon: '🎯', tags: ['hr', 'basics'], whatYouPractice: ['Common HR questions', 'Self-introduction', 'Answering "Why should we hire you?"', 'Professional tone'], whatAIMeasures: ['Answer relevance', 'Confidence level', 'Grammar accuracy', 'Response length'], sampleQuestion: 'Tell me about yourself and why you are interested in this role.', reviews: [{ name: 'Priya S.', text: 'Perfect for beginners! Helped me prepare for my first interview.', rating: 5 }, { name: 'Rahul K.', text: 'Clear feedback on every answer. Loved it!', rating: 5 }], prerequisites: [], sessionsCompleted: 48200 },
  { id: 'normal-talking', slug: 'normal-talking', title: 'Normal Talking', description: 'Casual real-life conversation with an AI friend. No pressure, no judgment. Just talk naturally and build fluency.', category: 'foundation', difficulty: 'beginner', duration: '5–10 min', rating: 4.7, icon: '💬', tags: ['casual', 'fluency'], whatYouPractice: ['Natural conversation flow', 'Casual vocabulary', 'Building fluency', 'Relaxed communication'], whatAIMeasures: ['Fluency score', 'Vocabulary range', 'Filler word count', 'Natural pauses'], sampleQuestion: 'What did you do last weekend? Tell me about something fun.', reviews: [{ name: 'Ankit M.', text: 'Felt like chatting with a friend. Great for building confidence.', rating: 5 }, { name: 'Sara L.', text: 'No pressure at all. Helped me open up.', rating: 4 }], prerequisites: [], sessionsCompleted: 35100 },
  { id: 'introduction-check', slug: 'introduction-check', title: 'Introduction Check Interview', description: 'Master the art of introducing yourself. Practice your name, background, goals, and first impressions in under 60 seconds.', category: 'foundation', difficulty: 'beginner', duration: '8 min', rating: 4.9, icon: '👋', tags: ['introduction', 'first-impression'], whatYouPractice: ['60-second self-intro', 'Name & background delivery', 'Goal articulation', 'First impression mastery'], whatAIMeasures: ['Clarity score', 'Time management', 'Confidence level', 'Structure quality'], sampleQuestion: 'Introduce yourself in 60 seconds — cover your name, background, and goals.', reviews: [{ name: 'Meera J.', text: 'I nailed my intro after just 3 sessions!', rating: 5 }, { name: 'Dev P.', text: 'Short but incredibly useful.', rating: 5 }], prerequisites: [], sessionsCompleted: 52300 },
  { id: 'self-presentation', slug: 'self-presentation', title: 'Self-Presentation Interview', description: 'Craft and deliver your personal elevator pitch. Learn to present yourself as a brand in 30, 60, and 90 second formats.', category: 'foundation', difficulty: 'beginner', duration: '10 min', rating: 4.8, icon: '🎤', tags: ['pitch', 'branding'], whatYouPractice: ['30/60/90 second pitches', 'Personal branding', 'Elevator pitch', 'Value proposition'], whatAIMeasures: ['Pitch clarity', 'Time adherence', 'Impact score', 'Persuasion level'], sampleQuestion: 'Give me your 60-second elevator pitch — who are you and what do you bring to the table?', reviews: [{ name: 'Kiran R.', text: 'Transformed how I present myself. Amazing!', rating: 5 }], prerequisites: [], sessionsCompleted: 31400 },
  { id: 'vocabulary-builder', slug: 'vocabulary-builder', title: 'Vocabulary Builder Interview', description: 'Use rich, professional vocabulary naturally in your answers. AI suggests better word choices in real-time.', category: 'foundation', difficulty: 'beginner', duration: '12 min', rating: 4.6, icon: '📚', tags: ['vocabulary', 'language'], whatYouPractice: ['Professional vocabulary', 'Word choice improvement', 'Synonym usage', 'Context-appropriate language'], whatAIMeasures: ['Vocabulary richness', 'Word sophistication', 'Context accuracy', 'Improvement rate'], sampleQuestion: 'Describe your biggest professional achievement using descriptive language.', reviews: [{ name: 'Aditi G.', text: 'My vocabulary improved so much in just a week!', rating: 5 }], prerequisites: [], sessionsCompleted: 22800 },
  { id: 'filler-word-eliminator', slug: 'filler-word-eliminator', title: 'Filler Word Eliminator', description: 'AI detects and counts every "umm", "like", "you know", "basically" and trains you to eliminate them completely.', category: 'foundation', difficulty: 'beginner', duration: '10 min', rating: 4.9, icon: '🚫', tags: ['filler-words', 'clarity'], whatYouPractice: ['Eliminating filler words', 'Confident pausing', 'Clean speech delivery', 'Conscious speaking'], whatAIMeasures: ['Filler word count', 'Filler frequency', 'Pause quality', 'Clarity improvement'], sampleQuestion: 'Why do you want to work in this industry? Speak for 2 minutes without any filler words.', reviews: [{ name: 'Varun T.', text: 'Dropped my filler words from 30 to 3 per session!', rating: 5 }], prerequisites: [], sessionsCompleted: 41600 },
  { id: 'grammar-correction', slug: 'grammar-correction', title: 'Grammar Correction Interview', description: 'Speak freely and AI instantly corrects grammar, tense, and sentence structure after each response.', category: 'foundation', difficulty: 'beginner', duration: '10 min', rating: 4.7, icon: '✏️', tags: ['grammar', 'correction'], whatYouPractice: ['Correct tense usage', 'Sentence structure', 'Subject-verb agreement', 'Professional grammar'], whatAIMeasures: ['Grammar accuracy', 'Error count', 'Tense consistency', 'Improvement rate'], sampleQuestion: 'Tell me about a project you worked on recently and what you learned.', reviews: [{ name: 'Sneha B.', text: 'Finally fixed my grammar mistakes. The AI catches everything!', rating: 5 }], prerequisites: [], sessionsCompleted: 28900 },
  { id: 'pronunciation-accent', slug: 'pronunciation-accent', title: 'Pronunciation & Accent Interview', description: 'AI evaluates your pronunciation clarity, accent, and phonetic accuracy. Improve word stress and intonation.', category: 'foundation', difficulty: 'beginner', duration: '12 min', rating: 4.8, icon: '🗣️', tags: ['pronunciation', 'accent'], whatYouPractice: ['Word stress patterns', 'Intonation control', 'Phonetic clarity', 'Accent neutralization'], whatAIMeasures: ['Pronunciation score', 'Clarity rating', 'Intonation accuracy', 'Stress patterns'], sampleQuestion: 'Read the following paragraph aloud with clear pronunciation and proper intonation.', reviews: [{ name: 'Amit D.', text: 'My pronunciation improved dramatically!', rating: 5 }], prerequisites: [], sessionsCompleted: 26400 },
  { id: 'first-job', slug: 'first-job', title: 'First Job Interview', description: 'Specifically designed for freshers and students with zero work experience. Covers academics, hobbies, goals, and potential.', category: 'foundation', difficulty: 'beginner', duration: '15 min', rating: 4.9, icon: '🎓', tags: ['fresher', 'first-job'], whatYouPractice: ['Discussing academics', 'Presenting hobbies as skills', 'Goal setting articulation', 'Showing potential'], whatAIMeasures: ['Relevance score', 'Enthusiasm level', 'Clarity', 'Growth mindset indicators'], sampleQuestion: 'You have no work experience. Why should we still consider you for this role?', reviews: [{ name: 'Pooja V.', text: 'Got my first job offer after practicing here!', rating: 5 }], prerequisites: [], sessionsCompleted: 55100 },
  { id: 'campus-placement', slug: 'campus-placement', title: 'Campus Placement Interview', description: 'Practice for college placement drives. Covers aptitude-based HR questions, company knowledge, and student-specific scenarios.', category: 'foundation', difficulty: 'beginner', duration: '20 min', rating: 4.9, icon: '🏫', tags: ['campus', 'placement'], whatYouPractice: ['Campus-style HR questions', 'Company research presentation', 'Aptitude-based answers', 'Student scenarios'], whatAIMeasures: ['Answer structure', 'Company knowledge', 'Confidence', 'Professional readiness'], sampleQuestion: 'Why do you want to join our company and how does your academic background align with this role?', reviews: [{ name: 'Rohit S.', text: 'Cracked my campus placement on the first try!', rating: 5 }], prerequisites: [], sessionsCompleted: 49800 },

  // ── COMMUNICATION MASTERY ──
  { id: 'confidence', slug: 'confidence', title: 'Confidence Interview', description: 'AI detects hesitation, low energy, and weak delivery. Trains you to answer boldly, maintain eye contact, and project authority.', category: 'communication', difficulty: 'intermediate', duration: '15 min', rating: 4.9, icon: '💪', tags: ['confidence', 'energy'], whatYouPractice: ['Bold answering', 'Energy projection', 'Authority in voice', 'Decisive language'], whatAIMeasures: ['Confidence score', 'Hesitation count', 'Energy level', 'Authority indicators'], sampleQuestion: 'Tell me about a time you had to take charge of a difficult situation.', reviews: [{ name: 'Arjun M.', text: 'This changed how I speak in interviews forever.', rating: 5 }], prerequisites: [], sessionsCompleted: 43200 },
  { id: 'communication', slug: 'communication', title: 'Communication Interview', description: 'Focus on clarity, structure, logical flow, and completeness of communication in every answer.', category: 'communication', difficulty: 'intermediate', duration: '15 min', rating: 4.8, icon: '📢', tags: ['clarity', 'structure'], whatYouPractice: ['Answer structuring', 'Logical flow', 'Completeness', 'Clarity of thought'], whatAIMeasures: ['Structure score', 'Logical flow', 'Completeness', 'Clarity rating'], sampleQuestion: 'Walk me through how you would plan and execute a team project from start to finish.', reviews: [{ name: 'Nisha K.', text: 'My answers are so much more structured now!', rating: 5 }], prerequisites: [], sessionsCompleted: 38700 },
  { id: 'voice-modulation', slug: 'voice-modulation', title: 'Voice Modulation Interview', description: 'Practice controlling your pitch, pace, volume, and pauses. Learn when to slow down, emphasize, and create impact.', category: 'communication', difficulty: 'intermediate', duration: '12 min', rating: 4.7, icon: '🎵', tags: ['voice', 'modulation'], whatYouPractice: ['Pitch variation', 'Pace control', 'Strategic pausing', 'Volume modulation'], whatAIMeasures: ['Pitch range', 'Pace consistency', 'Pause effectiveness', 'Volume variation'], sampleQuestion: 'Deliver this statement with emphasis on the key words and strategic pauses.', reviews: [{ name: 'Tanvi R.', text: 'I sound so much more engaging now!', rating: 4 }], prerequisites: [], sessionsCompleted: 19800 },
  { id: 'active-listening', slug: 'active-listening', title: 'Active Listening Interview', description: 'Multi-part complex questions are asked. You must listen carefully and answer all parts accurately without repetition.', category: 'communication', difficulty: 'intermediate', duration: '15 min', rating: 4.8, icon: '👂', tags: ['listening', 'attention'], whatYouPractice: ['Multi-part question handling', 'Detail retention', 'Comprehensive answering', 'No-repetition discipline'], whatAIMeasures: ['Parts addressed', 'Accuracy score', 'Repetition count', 'Comprehension level'], sampleQuestion: 'Describe your strongest technical skill, give an example of using it, and explain how it helped your team.', reviews: [{ name: 'Vikram J.', text: 'Trained me to actually listen before answering.', rating: 5 }], prerequisites: [], sessionsCompleted: 21500 },
  { id: 'emotional-intelligence', slug: 'emotional-intelligence', title: 'Emotional Intelligence Interview', description: 'Handle questions about failure, conflict, feedback, and sensitive topics with maturity, self-awareness, and empathy.', category: 'communication', difficulty: 'intermediate', duration: '20 min', rating: 4.9, icon: '🧠', tags: ['eq', 'empathy'], whatYouPractice: ['Handling failure questions', 'Conflict resolution narratives', 'Receiving feedback gracefully', 'Empathetic responses'], whatAIMeasures: ['Emotional maturity', 'Self-awareness', 'Empathy indicators', 'Conflict handling score'], sampleQuestion: 'Tell me about a time you received harsh feedback. How did you respond?', reviews: [{ name: 'Divya P.', text: 'This helped me handle tough questions with grace.', rating: 5 }], prerequisites: [], sessionsCompleted: 33100 },
  { id: 'storytelling', slug: 'storytelling', title: 'Storytelling Interview', description: 'Answer every question using the STAR method (Situation, Task, Action, Result) with narrative storytelling techniques.', category: 'communication', difficulty: 'intermediate', duration: '18 min', rating: 4.8, icon: '📖', tags: ['star', 'narrative'], whatYouPractice: ['STAR method mastery', 'Narrative structure', 'Engaging storytelling', 'Result quantification'], whatAIMeasures: ['STAR compliance', 'Story engagement', 'Result clarity', 'Narrative flow'], sampleQuestion: 'Using the STAR method, describe a challenge you overcame at work or school.', reviews: [{ name: 'Ravi G.', text: 'Mastered the STAR method in just 5 sessions!', rating: 5 }], prerequisites: [], sessionsCompleted: 29600 },
  { id: 'body-language', slug: 'body-language', title: 'Body Language Awareness Interview', description: 'Camera-on mode. AI analyzes your posture, gestures, facial expressions, and physical confidence cues.', category: 'communication', difficulty: 'intermediate', duration: '15 min', rating: 4.7, icon: '🧍', tags: ['body-language', 'posture'], whatYouPractice: ['Posture awareness', 'Gesture control', 'Facial expression management', 'Physical confidence'], whatAIMeasures: ['Posture score', 'Gesture appropriateness', 'Eye contact frequency', 'Confidence cues'], sampleQuestion: 'Present your career goals while maintaining confident body language.', reviews: [{ name: 'Ananya S.', text: 'Never realized how much my posture affected my interviews!', rating: 5 }], prerequisites: [], sessionsCompleted: 17200 },
  { id: 'eye-contact', slug: 'eye-contact', title: 'Eye Contact & Presence Interview', description: 'Trains you to maintain natural eye contact, control nervous movements, and command presence.', category: 'communication', difficulty: 'intermediate', duration: '12 min', rating: 4.6, icon: '👁️', tags: ['eye-contact', 'presence'], whatYouPractice: ['Natural eye contact', 'Nervous movement control', 'Commanding presence', 'Camera awareness'], whatAIMeasures: ['Eye contact duration', 'Movement frequency', 'Presence score', 'Composure rating'], sampleQuestion: 'Maintain eye contact with the camera and answer: What makes you unique?', reviews: [{ name: 'Lakshmi N.', text: 'Great for video interview preparation!', rating: 4 }], prerequisites: [], sessionsCompleted: 14300 },
  { id: 'tone-politeness', slug: 'tone-politeness', title: 'Tone & Politeness Interview', description: 'Practice formal, semi-formal, and professional tone. AI flags rude, aggressive, or too-casual language.', category: 'communication', difficulty: 'intermediate', duration: '10 min', rating: 4.7, icon: '🤝', tags: ['tone', 'politeness'], whatYouPractice: ['Formal tone', 'Professional language', 'Polite phrasing', 'Tone switching'], whatAIMeasures: ['Tone appropriateness', 'Politeness score', 'Formality level', 'Language flags'], sampleQuestion: 'Your manager gives you feedback you disagree with. How do you respond professionally?', reviews: [{ name: 'Sanjay M.', text: 'Helped me sound more professional and polished.', rating: 5 }], prerequisites: [], sessionsCompleted: 18900 },
  { id: 'one-to-one', slug: 'one-to-one', title: 'One-to-One Conversation', description: 'Simulate a natural, flowing real-life conversation with an AI person. Covers greetings, opinions, discussions, and wrap-ups.', category: 'communication', difficulty: 'intermediate', duration: '15 min', rating: 4.8, icon: '🗨️', tags: ['conversation', 'social'], whatYouPractice: ['Greeting etiquette', 'Opinion sharing', 'Discussion flow', 'Graceful wrap-ups'], whatAIMeasures: ['Conversation flow', 'Engagement level', 'Topic transitions', 'Social skills score'], sampleQuestion: 'Let\'s have a casual conversation — what are your thoughts on remote work?', reviews: [{ name: 'Maya R.', text: 'Feels like a real conversation. Very natural!', rating: 5 }], prerequisites: [], sessionsCompleted: 25700 },

  // ── PERSUASION & INFLUENCE ──
  { id: 'convincing', slug: 'convincing', title: 'Convincing Interview', description: 'Practice persuading the interviewer using logic, emotion, data, and storytelling. Master the art of changing minds.', category: 'persuasion', difficulty: 'intermediate', duration: '18 min', rating: 4.8, icon: '🎯', tags: ['persuasion', 'influence'], whatYouPractice: ['Logical persuasion', 'Emotional appeal', 'Data-backed arguments', 'Mind-changing techniques'], whatAIMeasures: ['Persuasion effectiveness', 'Logic score', 'Emotional impact', 'Argument strength'], sampleQuestion: 'Convince me why your approach is better than the traditional method.', reviews: [{ name: 'Arun V.', text: 'My negotiation skills improved dramatically!', rating: 5 }], prerequisites: [], sessionsCompleted: 21300 },
  { id: 'negotiation', slug: 'negotiation', title: 'Negotiation Interview', description: 'Salary negotiation, role negotiation, deadline negotiation. Learn win-win communication strategies under pressure.', category: 'persuasion', difficulty: 'advanced', duration: '20 min', rating: 4.9, icon: '💰', tags: ['negotiation', 'salary'], whatYouPractice: ['Salary negotiation', 'Win-win strategies', 'Counter-offer techniques', 'Value articulation'], whatAIMeasures: ['Negotiation skill', 'Composure', 'Strategy effectiveness', 'Outcome quality'], sampleQuestion: 'We can offer you 15% less than your expected salary. How do you respond?', reviews: [{ name: 'Deepak L.', text: 'Negotiated a 25% higher salary after practicing here!', rating: 5 }], prerequisites: ['confidence', 'convincing'], sessionsCompleted: 27800 },
  { id: 'sales-pitch', slug: 'sales-pitch', title: 'Sales Pitch Interview', description: 'Sell a product, a service, an idea, or yourself in 60 seconds. Master hooks, value propositions, and closing lines.', category: 'persuasion', difficulty: 'advanced', duration: '15 min', rating: 4.8, icon: '🛒', tags: ['sales', 'pitch'], whatYouPractice: ['Hook creation', 'Value proposition', 'Closing techniques', '60-second pitch'], whatAIMeasures: ['Hook effectiveness', 'Value clarity', 'Closing strength', 'Persuasion score'], sampleQuestion: 'Sell me this pen in 60 seconds. Go!', reviews: [{ name: 'Kavya S.', text: 'Made me think like a salesperson. Incredible!', rating: 5 }], prerequisites: [], sessionsCompleted: 19500 },
  { id: 'motivational-speaking', slug: 'motivational-speaking', title: 'Motivational Speaking Interview', description: 'Practice delivering short motivational talks. AI scores your energy, inspiration level, and audience impact.', category: 'persuasion', difficulty: 'advanced', duration: '15 min', rating: 4.7, icon: '🔥', tags: ['motivation', 'speaking'], whatYouPractice: ['Inspirational delivery', 'Energy projection', 'Audience connection', 'Call to action'], whatAIMeasures: ['Energy score', 'Inspiration level', 'Impact rating', 'Delivery quality'], sampleQuestion: 'Give a 2-minute motivational talk on the importance of never giving up.', reviews: [{ name: 'Ishaan K.', text: 'Found my voice as a speaker through this!', rating: 5 }], prerequisites: [], sessionsCompleted: 15600 },
  { id: 'diplomatic', slug: 'diplomatic', title: 'Diplomatic Interview', description: 'Answer politically sensitive or controversial questions with balance, tact, and professionalism.', category: 'persuasion', difficulty: 'advanced', duration: '20 min', rating: 4.8, icon: '⚖️', tags: ['diplomacy', 'tact'], whatYouPractice: ['Balanced responses', 'Tactful language', 'Controversy handling', 'Professional neutrality'], whatAIMeasures: ['Balance score', 'Tact level', 'Professionalism', 'Neutrality rating'], sampleQuestion: 'Your team is split 50/50 on a decision. How do you handle it without taking sides?', reviews: [{ name: 'Neha R.', text: 'Perfect for learning how to handle tricky questions.', rating: 5 }], prerequisites: [], sessionsCompleted: 13200 },

  // ── DEBATE & DEFENSE ──
  { id: 'debating', slug: 'debating', title: 'Debating Interview', description: 'Structured formal debate. AI takes the opposite side. Practice argument construction, rebuttals, and logical counter-points.', category: 'debate', difficulty: 'advanced', duration: '25 min', rating: 4.9, icon: '⚔️', tags: ['debate', 'argument'], whatYouPractice: ['Argument construction', 'Rebuttal techniques', 'Counter-point delivery', 'Logical reasoning'], whatAIMeasures: ['Argument strength', 'Rebuttal quality', 'Logic score', 'Composure'], sampleQuestion: 'Debate: "AI will replace most human jobs within 10 years." You argue FOR.', reviews: [{ name: 'Harsh P.', text: 'Best debate practice I\'ve ever had!', rating: 5 }], prerequisites: ['confidence'], sessionsCompleted: 24100 },
  { id: 'defending', slug: 'defending', title: 'Defending Interview', description: 'Defend your past decisions, career choices, project failures, or controversial opinions under intense questioning.', category: 'debate', difficulty: 'advanced', duration: '20 min', rating: 4.9, icon: '🛡️', tags: ['defense', 'justification'], whatYouPractice: ['Decision justification', 'Failure explanation', 'Career choice defense', 'Standing your ground'], whatAIMeasures: ['Defense strength', 'Composure', 'Logic', 'Conviction level'], sampleQuestion: 'You changed your career field twice. Defend that decision.', reviews: [{ name: 'Ritika M.', text: 'Taught me to own my decisions confidently.', rating: 5 }], prerequisites: [], sessionsCompleted: 20300 },
  { id: 'devils-advocate', slug: 'devils-advocate', title: "Devil's Advocate Interview", description: 'Every answer you give, the AI immediately challenges it. Stay composed, logical, and confident under sustained pressure.', category: 'debate', difficulty: 'advanced', duration: '20 min', rating: 4.8, icon: '😈', tags: ['challenge', 'pressure'], whatYouPractice: ['Handling challenges', 'Sustained composure', 'Adaptive reasoning', 'Pressure management'], whatAIMeasures: ['Composure score', 'Adaptability', 'Logic consistency', 'Pressure handling'], sampleQuestion: 'Why is your approach better? (AI will challenge every response you give)', reviews: [{ name: 'Siddharth J.', text: 'Extremely challenging but incredibly rewarding!', rating: 5 }], prerequisites: ['confidence', 'debating'], sessionsCompleted: 18700 },
  { id: 'stress', slug: 'stress', title: 'Stress Interview', description: 'AI acts as an intentionally rude, dismissive, or aggressive interviewer. Practice staying calm, professional, and sharp.', category: 'debate', difficulty: 'advanced', duration: '20 min', rating: 4.9, icon: '😤', tags: ['stress', 'pressure'], whatYouPractice: ['Calm under pressure', 'Professional responses to rudeness', 'Composure maintenance', 'Sharp thinking under stress'], whatAIMeasures: ['Stress handling', 'Professionalism', 'Composure', 'Response quality under pressure'], sampleQuestion: 'I don\'t think you\'re qualified for this role at all. Change my mind.', reviews: [{ name: 'Kunal B.', text: 'Intense but prepared me for the worst-case scenario.', rating: 5 }], prerequisites: ['confidence'], sessionsCompleted: 31200 },
  { id: 'critical-thinking', slug: 'critical-thinking', title: 'Critical Thinking Interview', description: 'Rapid-fire analytical, logical, and problem-solving questions. Think on your feet and structure answers instantly.', category: 'debate', difficulty: 'advanced', duration: '20 min', rating: 4.8, icon: '⚡', tags: ['analytical', 'logic'], whatYouPractice: ['Rapid analysis', 'Logical structuring', 'On-the-spot thinking', 'Problem decomposition'], whatAIMeasures: ['Speed of response', 'Logic quality', 'Structure score', 'Analysis depth'], sampleQuestion: 'How many tennis balls can fit in this room? Walk me through your logic.', reviews: [{ name: 'Pranav T.', text: 'Sharpened my analytical thinking like nothing else!', rating: 5 }], prerequisites: [], sessionsCompleted: 22900 },
  { id: 'philosophy-ethics', slug: 'philosophy-ethics', title: 'Philosophy & Ethics Interview', description: 'Deep moral and philosophical questions. Practice forming, defending, and evolving your personal viewpoint live.', category: 'debate', difficulty: 'advanced', duration: '25 min', rating: 4.7, icon: '🏛️', tags: ['philosophy', 'ethics'], whatYouPractice: ['Forming viewpoints', 'Ethical reasoning', 'Perspective evolution', 'Deep critical thought'], whatAIMeasures: ['Depth of thought', 'Ethical reasoning', 'Perspective quality', 'Articulation'], sampleQuestion: 'Is it ever ethical to lie? Defend your position.', reviews: [{ name: 'Simran K.', text: 'Made me think deeper than any interview ever has.', rating: 5 }], prerequisites: [], sessionsCompleted: 11200 },

  // ── SCENARIO & ROLE-PLAY ──
  { id: 'traffic-police', slug: 'traffic-police', title: 'Traffic Police Interview', description: 'Role-play: You\'re stopped by a traffic officer. Practice formal, calm, and respectful authority communication.', category: 'roleplay', difficulty: 'intermediate', duration: '10 min', rating: 4.6, icon: '🚔', tags: ['authority', 'roleplay'], whatYouPractice: ['Authority communication', 'Calm responses', 'Respectful tone', 'Formal language'], whatAIMeasures: ['Tone appropriateness', 'Respect level', 'Composure', 'Formality'], sampleQuestion: 'Officer: "Do you know why I pulled you over?" Respond calmly and professionally.', reviews: [{ name: 'Ajay R.', text: 'Fun and practical at the same time!', rating: 4 }], prerequisites: [], sessionsCompleted: 9800 },
  { id: 'customer-handling', slug: 'customer-handling', title: 'Customer Handling Interview', description: 'You are a customer service representative. Handle angry, confused, or demanding customer scenarios professionally.', category: 'roleplay', difficulty: 'intermediate', duration: '15 min', rating: 4.8, icon: '🎧', tags: ['customer-service', 'handling'], whatYouPractice: ['De-escalation', 'Problem resolution', 'Empathetic responses', 'Professional patience'], whatAIMeasures: ['De-escalation skill', 'Resolution quality', 'Empathy score', 'Patience level'], sampleQuestion: 'An angry customer demands a refund for a non-refundable product. How do you handle it?', reviews: [{ name: 'Swati M.', text: 'Essential for anyone in customer-facing roles!', rating: 5 }], prerequisites: [], sessionsCompleted: 23400 },
  { id: 'doctor-patient', slug: 'doctor-patient', title: 'Doctor & Patient Interview', description: 'Practice formal, empathetic, and structured medical consultation communication on both sides.', category: 'roleplay', difficulty: 'advanced', duration: '20 min', rating: 4.7, icon: '🏥', tags: ['medical', 'empathy'], whatYouPractice: ['Medical communication', 'Empathetic delivery', 'Structured consultation', 'Patient handling'], whatAIMeasures: ['Empathy score', 'Clarity', 'Professionalism', 'Structure quality'], sampleQuestion: 'A patient is anxious about a diagnosis. How do you explain the situation calmly?', reviews: [{ name: 'Dr. Patel', text: 'Great for medical communication training.', rating: 5 }], prerequisites: [], sessionsCompleted: 12100 },
  { id: 'legal-courtroom', slug: 'legal-courtroom', title: 'Legal / Courtroom Interview', description: 'Simulate formal legal questioning. Practice structured, precise, and professional courtroom communication.', category: 'roleplay', difficulty: 'advanced', duration: '25 min', rating: 4.7, icon: '⚖️', tags: ['legal', 'courtroom'], whatYouPractice: ['Legal language', 'Precise answering', 'Structured arguments', 'Courtroom etiquette'], whatAIMeasures: ['Precision', 'Legal language usage', 'Structure', 'Professionalism'], sampleQuestion: 'The prosecution claims your client was negligent. Present your defense argument.', reviews: [{ name: 'Adv. Sharma', text: 'Excellent for law students preparing for moot court.', rating: 5 }], prerequisites: [], sessionsCompleted: 8900 },
  { id: 'teacher-student', slug: 'teacher-student', title: 'Teacher & Student Interview', description: 'Role-play academic scenarios: defending your assignment, explaining your understanding, handling academic disputes.', category: 'roleplay', difficulty: 'intermediate', duration: '15 min', rating: 4.6, icon: '📝', tags: ['academic', 'teaching'], whatYouPractice: ['Academic defense', 'Explanation skills', 'Dispute handling', 'Knowledge articulation'], whatAIMeasures: ['Explanation clarity', 'Knowledge depth', 'Defense quality', 'Academic communication'], sampleQuestion: 'Your professor questions your research methodology. Defend your approach.', reviews: [{ name: 'Prof. Gupta', text: 'Great practice for student presentations.', rating: 4 }], prerequisites: [], sessionsCompleted: 11500 },
  { id: 'media-press', slug: 'media-press', title: 'Media & Press Interview', description: 'Practice being interviewed by a journalist. Handle tricky media questions, spin positively, and stay on message.', category: 'roleplay', difficulty: 'advanced', duration: '20 min', rating: 4.8, icon: '📰', tags: ['media', 'press'], whatYouPractice: ['Media handling', 'Positive spin', 'Staying on message', 'Sound bite creation'], whatAIMeasures: ['Message consistency', 'Spin effectiveness', 'Composure', 'Sound bite quality'], sampleQuestion: 'Reports say your company is failing. How do you respond to these allegations?', reviews: [{ name: 'Kriti S.', text: 'Perfect for PR and communication roles!', rating: 5 }], prerequisites: [], sessionsCompleted: 14700 },
  { id: 'police-interrogation', slug: 'police-interrogation', title: 'Police Interrogation Interview', description: 'High-pressure role-play where you must stay calm, honest, and composed under intense questioning.', category: 'roleplay', difficulty: 'advanced', duration: '20 min', rating: 4.7, icon: '🔍', tags: ['interrogation', 'pressure'], whatYouPractice: ['Calm under pressure', 'Honest communication', 'Composure', 'Clear articulation'], whatAIMeasures: ['Stress handling', 'Honesty indicators', 'Composure score', 'Clarity'], sampleQuestion: 'Where were you last night between 8 PM and 11 PM? Be specific.', reviews: [{ name: 'Mohit K.', text: 'The most intense practice session I\'ve done!', rating: 5 }], prerequisites: ['stress'], sessionsCompleted: 16300 },
  { id: 'immigration-visa', slug: 'immigration-visa', title: 'Immigration & Visa Interview', description: 'Practice answering immigration officer questions calmly, clearly, and correctly in formal English.', category: 'roleplay', difficulty: 'intermediate', duration: '15 min', rating: 4.8, icon: '✈️', tags: ['visa', 'immigration'], whatYouPractice: ['Formal English', 'Document-based answers', 'Calm delivery', 'Clarity under authority'], whatAIMeasures: ['Accuracy', 'Formality', 'Composure', 'Clarity'], sampleQuestion: 'What is the purpose of your visit and how long do you plan to stay?', reviews: [{ name: 'Fatima A.', text: 'Passed my visa interview with confidence!', rating: 5 }], prerequisites: [], sessionsCompleted: 28600 },
  { id: 'business-meeting', slug: 'business-meeting', title: 'Business Meeting Simulation', description: 'Practice presenting ideas, handling objections, and leading or contributing to professional meetings.', category: 'roleplay', difficulty: 'advanced', duration: '25 min', rating: 4.8, icon: '💼', tags: ['business', 'meeting'], whatYouPractice: ['Idea presentation', 'Objection handling', 'Meeting leadership', 'Professional contribution'], whatAIMeasures: ['Presentation quality', 'Objection handling', 'Leadership indicators', 'Contribution score'], sampleQuestion: 'Present your quarterly plan to the board and handle their objections.', reviews: [{ name: 'Rajesh T.', text: 'Transformed how I lead meetings at work.', rating: 5 }], prerequisites: [], sessionsCompleted: 17800 },

  // ── PROFESSIONAL & CAREER ──
  { id: 'take-interview', slug: 'take-interview', title: 'Take Interview (Be the Interviewer)', description: 'You ask the questions. Practice formulating smart, structured, and insightful interview questions like an HR pro.', category: 'professional', difficulty: 'advanced', duration: '20 min', rating: 4.8, icon: '🎙️', tags: ['interviewer', 'hr'], whatYouPractice: ['Question formulation', 'Interview structure', 'Candidate evaluation', 'HR perspective'], whatAIMeasures: ['Question quality', 'Structure', 'Depth of questions', 'Interview flow'], sampleQuestion: 'You are the interviewer. Ask the candidate about their biggest professional failure.', reviews: [{ name: 'HR Nandini', text: 'Great for understanding the other side of the table!', rating: 5 }], prerequisites: [], sessionsCompleted: 19200 },
  { id: 'hr-round', slug: 'hr-round', title: 'HR Round Interview', description: 'Behavioral + situational + culture-fit questions. STAR method answers, team conflict scenarios, and goal-setting.', category: 'professional', difficulty: 'intermediate', duration: '20 min', rating: 4.9, icon: '👔', tags: ['hr', 'behavioral'], whatYouPractice: ['Behavioral questions', 'Situational responses', 'Culture-fit answers', 'STAR method'], whatAIMeasures: ['STAR compliance', 'Cultural alignment', 'Behavioral indicators', 'Answer depth'], sampleQuestion: 'Tell me about a time you had a conflict with a team member. How did you resolve it?', reviews: [{ name: 'Anjali D.', text: 'The most realistic HR round simulation!', rating: 5 }], prerequisites: [], sessionsCompleted: 45600 },
  { id: 'technical-simulation', slug: 'technical-simulation', title: 'Technical Interview Simulation', description: 'Domain-specific technical questions for your chosen field: IT, Engineering, Finance, Marketing, Design, etc.', category: 'professional', difficulty: 'advanced', duration: '30 min', rating: 4.8, icon: '💻', tags: ['technical', 'domain'], whatYouPractice: ['Domain knowledge', 'Technical articulation', 'Problem-solving explanation', 'Concept clarity'], whatAIMeasures: ['Technical accuracy', 'Explanation quality', 'Depth of knowledge', 'Problem-solving approach'], sampleQuestion: 'Explain the difference between SQL and NoSQL databases and when you would use each.', reviews: [{ name: 'Suresh V.', text: 'Covers every technical domain perfectly.', rating: 5 }], prerequisites: [], sessionsCompleted: 38900 },
  { id: 'leadership', slug: 'leadership', title: 'Leadership Interview', description: 'Demonstrate vision, strategic thinking, conflict resolution, team motivation, and executive presence.', category: 'professional', difficulty: 'advanced', duration: '25 min', rating: 4.9, icon: '👑', tags: ['leadership', 'executive'], whatYouPractice: ['Vision articulation', 'Strategic thinking', 'Team motivation', 'Executive presence'], whatAIMeasures: ['Leadership indicators', 'Vision clarity', 'Strategic depth', 'Motivational ability'], sampleQuestion: 'Your team is demotivated after a project failure. How do you re-energize them?', reviews: [{ name: 'Manish S.', text: 'Helped me prepare for my VP-level interview.', rating: 5 }], prerequisites: ['confidence', 'hr-round'], sessionsCompleted: 21700 },
  { id: 'panel-interview', slug: 'panel-interview', title: 'Panel Interview Simulation', description: '3 AI interviewers ask questions simultaneously from different roles. Manage attention, direction, and composure.', category: 'professional', difficulty: 'advanced', duration: '30 min', rating: 4.9, icon: '👥', tags: ['panel', 'multi-interviewer'], whatYouPractice: ['Multi-interviewer management', 'Attention distribution', 'Composure under observation', 'Diverse question handling'], whatAIMeasures: ['Attention management', 'Composure', 'Answer diversity', 'Engagement with all interviewers'], sampleQuestion: 'Interviewer 1 asks about your technical skills, while Interviewer 2 asks about teamwork. Address both.', reviews: [{ name: 'Aditya R.', text: 'Nothing else prepares you for panel interviews like this!', rating: 5 }], prerequisites: ['hr-round', 'technical-simulation'], sessionsCompleted: 16500 },
  { id: 'internship', slug: 'internship', title: 'Internship Interview', description: 'Freshers-focused. Academic background, skill readiness, motivation, and learning attitude questions.', category: 'professional', difficulty: 'beginner', duration: '15 min', rating: 4.8, icon: '📋', tags: ['internship', 'fresher'], whatYouPractice: ['Academic presentation', 'Skill readiness', 'Motivation articulation', 'Learning attitude'], whatAIMeasures: ['Enthusiasm', 'Skill awareness', 'Learning indicators', 'Cultural fit'], sampleQuestion: 'What skills do you hope to develop during this internship?', reviews: [{ name: 'Preeti L.', text: 'Got my dream internship after 4 sessions!', rating: 5 }], prerequisites: [], sessionsCompleted: 42300 },
  { id: 'promotion-appraisal', slug: 'promotion-appraisal', title: 'Promotion / Appraisal Interview', description: 'Make the case for your promotion. Practice self-advocacy, performance narration, and future vision.', category: 'professional', difficulty: 'advanced', duration: '20 min', rating: 4.8, icon: '📈', tags: ['promotion', 'appraisal'], whatYouPractice: ['Self-advocacy', 'Performance narration', 'Future vision', 'Value demonstration'], whatAIMeasures: ['Advocacy strength', 'Evidence quality', 'Vision clarity', 'Confidence'], sampleQuestion: 'Why do you believe you deserve a promotion this quarter?', reviews: [{ name: 'Geeta K.', text: 'Used this to prepare for my appraisal and got promoted!', rating: 5 }], prerequisites: [], sessionsCompleted: 24800 },
  { id: 'entrepreneurship-pitch', slug: 'entrepreneurship-pitch', title: 'Entrepreneurship Pitch Interview', description: 'Pitch your startup idea to an AI investor. Handle due diligence, competition questions, and valuation discussions.', category: 'professional', difficulty: 'advanced', duration: '25 min', rating: 4.9, icon: '🚀', tags: ['startup', 'investor-pitch'], whatYouPractice: ['Startup pitching', 'Due diligence handling', 'Competition analysis', 'Valuation discussion'], whatAIMeasures: ['Pitch quality', 'Market understanding', 'Financial awareness', 'Persuasion'], sampleQuestion: 'You have 5 minutes to pitch your startup. Why should I invest $1M in your idea?', reviews: [{ name: 'Vikrant C.', text: 'The most realistic investor pitch simulation ever!', rating: 5 }], prerequisites: ['sales-pitch'], sessionsCompleted: 18300 },

  // ── AI-SPECIAL MODES ──
  { id: 'error-check', slug: 'error-check', title: 'Error Check Interview', description: 'AI flags every error live: grammar, filler words, weak logic, unclear answers, off-topic responses — full report at end.', category: 'ai-special', difficulty: 'intermediate', duration: '15 min', rating: 4.9, icon: '🔎', tags: ['error-detection', 'comprehensive'], whatYouPractice: ['Error-free speaking', 'Self-monitoring', 'Comprehensive improvement', 'Quality awareness'], whatAIMeasures: ['Total error count', 'Error categories', 'Improvement over time', 'Overall quality'], sampleQuestion: 'Answer the following 5 questions. AI will track every error in real-time.', reviews: [{ name: 'Naveen G.', text: 'The detailed error report at the end is invaluable!', rating: 5 }], prerequisites: [], sessionsCompleted: 37200 },
  { id: 'mirror-mode', slug: 'mirror-mode', title: 'Mirror Mode Interview', description: 'AI mirrors your exact speaking style and shows you how you sound to others. Shocking and transformative.', category: 'ai-special', difficulty: 'advanced', duration: '15 min', rating: 4.8, icon: '🪞', tags: ['self-awareness', 'mirror'], whatYouPractice: ['Self-perception', 'Speaking style awareness', 'Habit recognition', 'Style improvement'], whatAIMeasures: ['Style analysis', 'Pattern recognition', 'Habit frequency', 'Self-awareness score'], sampleQuestion: 'Speak for 2 minutes on any topic. Then hear how you sound played back to you.', reviews: [{ name: 'Roshni P.', text: 'Mind-blowing! Never knew I sounded like that.', rating: 5 }], prerequisites: [], sessionsCompleted: 14800 },
  { id: 'speed-round', slug: 'speed-round', title: 'Speed Round Interview', description: '30-second answer limit per question. Train rapid, clear, confident responses under strict time pressure.', category: 'ai-special', difficulty: 'advanced', duration: '10 min', rating: 4.8, icon: '⏱️', tags: ['speed', 'quick-thinking'], whatYouPractice: ['Rapid responses', 'Concise answering', 'Time management', 'Quick thinking'], whatAIMeasures: ['Response time', 'Clarity under pressure', 'Conciseness', 'Quality vs speed'], sampleQuestion: 'You have 30 seconds: What is your biggest strength and give one example?', reviews: [{ name: 'Aman S.', text: 'Trains your brain to think and speak fast!', rating: 5 }], prerequisites: [], sessionsCompleted: 26100 },
  { id: 'multilingual', slug: 'multilingual', title: 'Multilingual Interview', description: 'Practice switching between English and your native language professionally within an interview context.', category: 'ai-special', difficulty: 'intermediate', duration: '15 min', rating: 4.7, icon: '🌍', tags: ['multilingual', 'language-switch'], whatYouPractice: ['Language switching', 'Bilingual professional communication', 'Code-switching etiquette', 'Multilingual confidence'], whatAIMeasures: ['Switch smoothness', 'Language accuracy', 'Professional tone in both', 'Transition quality'], sampleQuestion: 'Answer this question first in English, then switch to your native language seamlessly.', reviews: [{ name: 'Priyanka T.', text: 'Perfect for bilingual interview environments!', rating: 5 }], prerequisites: [], sessionsCompleted: 13400 },
  { id: 'blind-interview', slug: 'blind-interview', title: 'Blind Interview', description: 'Questions appear one by one with no preview. Trains spontaneous, unprepared, natural answering ability.', category: 'ai-special', difficulty: 'advanced', duration: '20 min', rating: 4.8, icon: '🎲', tags: ['spontaneous', 'unprepared'], whatYouPractice: ['Spontaneous answering', 'Natural responses', 'Adaptability', 'Unprepared speaking'], whatAIMeasures: ['Spontaneity', 'Answer quality', 'Adaptability score', 'Natural flow'], sampleQuestion: '(Hidden until revealed) Be ready for anything!', reviews: [{ name: 'Diya J.', text: 'The closest simulation to a real unexpected interview!', rating: 5 }], prerequisites: [], sessionsCompleted: 20700 },
  { id: 'group-discussion', slug: 'group-discussion', title: 'Group Discussion Simulation', description: 'Multi-AI participants in a group discussion. Practice interrupting politely, leading, summarizing, and contributing.', category: 'ai-special', difficulty: 'advanced', duration: '25 min', rating: 4.9, icon: '🗣️', tags: ['gd', 'group'], whatYouPractice: ['Polite interruption', 'Discussion leadership', 'Summarization', 'Active contribution'], whatAIMeasures: ['Contribution quality', 'Leadership indicators', 'Interruption politeness', 'Summary accuracy'], sampleQuestion: 'Topic: "Should social media be regulated?" Join the group discussion.', reviews: [{ name: 'Tara N.', text: 'The multi-AI participants feel incredibly real!', rating: 5 }], prerequisites: [], sessionsCompleted: 29400 },
]

export const filterCategories = [
  { key: 'all', label: 'All', icon: '🔵' },
  { key: 'beginner', label: 'Beginner', icon: '🟢' },
  { key: 'intermediate', label: 'Intermediate', icon: '🟡' },
  { key: 'advanced', label: 'Advanced', icon: '🔴' },
  { key: 'roleplay', label: 'Role Play', icon: '🎭' },
  { key: 'communication', label: 'Communication', icon: '💬' },
  { key: 'debate', label: 'Critical Thinking', icon: '🧠' },
  { key: 'professional', label: 'Professional', icon: '💼' },
  { key: 'ai-special', label: 'AI Special', icon: '🤖' },
  { key: 'trending', label: 'Trending', icon: '🔥' },
  { key: 'recommended', label: 'Recommended', icon: '⭐' },
  { key: 'favourites', label: 'Favourites', icon: '❤️' },
  { key: 'completed', label: 'Completed', icon: '✅' },
  { key: 'locked', label: 'Locked', icon: '🔒' },
]

export function fuzzyMatch(text: string, query: string): boolean {
  const lower = text.toLowerCase()
  const q = query.toLowerCase()
  let qi = 0
  for (let i = 0; i < lower.length && qi < q.length; i++) {
    if (lower[i] === q[qi]) qi++
  }
  return qi === q.length
}
