import React, { useState } from 'react'
import { motion } from 'framer-motion'
import { Card } from '@/components/ui/card'
import { Button } from '@/components/ui/button'
import { Download, Rocket, Trophy, Terminal, FileCode2, Copy, FolderOpen, RefreshCcw, CheckCircle, Code2 } from 'lucide-react'
import JSZip from 'jszip'
import { toast } from 'sonner'
import { CurriculumData } from '@/app/dashboard/project-builder/page'

export default function ProjectComplete({
    curriculum,
    onRestart
}: {
    curriculum: CurriculumData,
    onRestart: () => void
}) {
    const [isDownloading, setIsDownloading] = useState(false)
    const [copiedFile, setCopiedFile] = useState<string | null>(null)

    const downloadZip = async () => {
        setIsDownloading(true)
        try {
            const zip = new JSZip()

            const folderName = curriculum.projectTitle.toLowerCase().replace(/[^a-z0-9]/g, '-')
            const projectFolder = zip.folder(folderName)

            if (projectFolder) {
                // Add final code files
                if (curriculum.finalProjectCode && curriculum.finalProjectCode.length > 0) {
                    curriculum.finalProjectCode.forEach(file => {
                        projectFolder.file(file.filename, file.code)
                    })
                }

                // Add README.md
                const readmeContent = curriculum.readmeContent || `# ${curriculum.projectTitle}\n\nGenerated by Intervyxa Coding Projects.`
                projectFolder.file('README.md', readmeContent)
            }

            const blob = await zip.generateAsync({ type: 'blob' })

            const url = window.URL.createObjectURL(blob)
            const a = document.createElement('a')
            a.href = url
            a.download = `${curriculum.projectTitle.toLowerCase().replace(/[^a-z0-9]/g, '-')}.zip`
            document.body.appendChild(a)
            a.click()

            window.URL.revokeObjectURL(url)
            document.body.removeChild(a)
            toast.success('Project downloaded successfully!')

        } catch (error) {
            console.error(error)
            toast.error('Failed to generate ZIP file')
        } finally {
            setIsDownloading(false)
        }
    }

    const copyToClipboard = (code: string, filename: string) => {
        navigator.clipboard.writeText(code)
        setCopiedFile(filename)
        toast.success(`Copied ${filename} to clipboard!`)
        setTimeout(() => setCopiedFile(null), 2000)
    }

    return (
        <div className="w-full max-w-7xl mx-auto py-12 px-4">
            {/* Top Celebration Section */}
            <div className="flex flex-col items-center text-center mb-16">
                <motion.div
                    initial={{ scale: 0 }}
                    animate={{ scale: 1 }}
                    transition={{ type: "spring", stiffness: 200, damping: 15 }}
                    className="w-40 h-40 rounded-full bg-emerald-500/10 flex items-center justify-center border-4 border-emerald-500/30 shadow-[0_0_80px_rgba(16,185,129,0.4)] mb-8"
                >
                    <Trophy className="w-20 h-20 text-emerald-400" />
                </motion.div>

                <div className="inline-flex items-center gap-2 px-4 py-1.5 rounded-full bg-indigo-500/10 border border-indigo-500/20 text-indigo-400 text-sm font-bold uppercase tracking-wider mb-6">
                    <CheckCircle className="w-4 h-4" /> Project Complete
                </div>

                <h1 className="text-5xl md:text-6xl font-black text-white tracking-tight leading-tight mb-6">
                    You built <span className="text-emerald-400">{curriculum.projectTitle}</span>!
                </h1>

                <p className="text-zinc-400 text-xl max-w-2xl leading-relaxed mb-10">
                    Incredible work! You've gone from zero to a fully functional project in <strong className="text-white">{curriculum.language}</strong>. Your final code has been assembled and is ready to run locally on your machine.
                </p>

                <div className="flex flex-col sm:flex-row gap-4 w-full max-w-md justify-center">
                    <Button
                        onClick={downloadZip}
                        disabled={isDownloading}
                        className="h-14 px-8 rounded-2xl bg-emerald-500 hover:bg-emerald-400 text-black font-bold shadow-[0_0_30px_rgba(16,185,129,0.3)] hover:shadow-[0_0_40px_rgba(16,185,129,0.5)] transition-all hover:-translate-y-1 text-lg"
                    >
                        {isDownloading ? 'Zipping Files...' : 'Download Project ZIP'} <Download className="w-5 h-5 ml-2" />
                    </Button>
                    <Button
                        variant="outline"
                        onClick={onRestart}
                        className="h-14 px-8 rounded-2xl border-white/10 text-zinc-300 hover:text-white hover:bg-white/5 font-bold"
                    >
                        <RefreshCcw className="w-4 h-4 mr-2" /> Start New Project
                    </Button>
                </div>
            </div>

            {/* Bottom Section: Split Workspace View & Instructions */}
            <div className="flex flex-col lg:flex-row gap-8 items-stretch">

                {/* File Tree & Code Preview */}
                <div className="w-full lg:w-1/2">
                    <Card className="bg-zinc-950/80 backdrop-blur-xl border border-white/10 rounded-3xl overflow-hidden h-full flex flex-col shadow-2xl">
                        <div className="p-6 border-b border-white/10 bg-zinc-900/50">
                            <h3 className="flex items-center gap-3 text-xl font-black text-white">
                                <FolderOpen className="w-6 h-6 text-amber-400" /> Compiled Workspace
                            </h3>
                            <p className="text-zinc-500 text-sm mt-2">All the files generated throughout your modules.</p>
                        </div>

                        <div className="flex-1 p-6 space-y-4 overflow-y-auto custom-scrollbar max-h-[600px]">
                            {curriculum.finalProjectCode?.map((file, i) => (
                                <div key={i} className="bg-zinc-900 border border-white/5 rounded-2xl overflow-hidden group">
                                    <div className="h-12 bg-zinc-800/50 border-b border-white/5 flex items-center justify-between px-4">
                                        <div className="flex items-center gap-2">
                                            <FileCode2 className="w-5 h-5 text-indigo-400" />
                                            <span className="font-mono text-sm font-bold text-white">{file.filename}</span>
                                        </div>
                                        <Button
                                            variant="ghost"
                                            size="sm"
                                            onClick={() => copyToClipboard(file.code, file.filename)}
                                            className="h-8 text-zinc-400 hover:text-white group-hover:opacity-100 opacity-50 transition-opacity"
                                        >
                                            {copiedFile === file.filename ? <CheckCircle className="w-4 h-4 text-emerald-400" /> : <Copy className="w-4 h-4" />}
                                        </Button>
                                    </div>
                                    <div className="p-4 bg-black/50 overflow-x-auto custom-scrollbar">
                                        <pre className="font-mono text-xs text-zinc-300">
                                            <code>{file.code.length > 500 ? file.code.substring(0, 500) + '\n... [truncated for display, full length in ZIP]' : file.code}</code>
                                        </pre>
                                    </div>
                                </div>
                            ))}
                        </div>
                    </Card>
                </div>

                {/* Local Setup Instructions */}
                <div className="w-full lg:w-1/2">
                    <Card className="bg-zinc-950/80 backdrop-blur-xl border border-white/10 rounded-3xl overflow-hidden h-full flex flex-col shadow-2xl">
                        <div className="p-6 border-b border-white/10 bg-zinc-900/50">
                            <h3 className="flex items-center gap-3 text-xl font-black text-white">
                                <Terminal className="w-6 h-6 text-emerald-400" /> Local Setup Guide
                            </h3>
                            <p className="text-zinc-500 text-sm mt-2">How to run this project on your own machine.</p>
                        </div>

                        <div className="flex-1 p-6 space-y-8 overflow-y-auto custom-scrollbar max-h-[600px]">

                            {/* Terminal Commands */}
                            <div>
                                <h4 className="font-bold text-white mb-4 flex items-center gap-2 uppercase tracking-widest text-sm text-zinc-400">
                                    <Terminal className="w-4 h-4 text-emerald-500" /> Terminal Commands
                                </h4>
                                <div className="space-y-3">
                                    {curriculum.runInstructions?.windows?.map((step, idx) => (
                                        <div key={idx} className="bg-black border border-white/10 rounded-xl p-4 font-mono text-sm">
                                            <span className="text-emerald-500 select-none mr-3">$</span>
                                            <span className="text-zinc-300">{step}</span>
                                        </div>
                                    ))}
                                    {(!curriculum.runInstructions?.windows || curriculum.runInstructions.windows.length === 0) && (
                                        <div className="text-zinc-500 italic text-sm">Extract the ZIP and run according to your environment.</div>
                                    )}
                                </div>
                            </div>

                            {/* VS Code Tips */}
                            <div>
                                <h4 className="font-bold text-white mb-4 flex items-center gap-2 uppercase tracking-widest text-sm text-zinc-400 mt-8 border-t border-white/10 pt-8">
                                    <Code2 className="w-4 h-4 text-blue-400" /> VS Code Environment
                                </h4>
                                <ul className="space-y-4">
                                    {curriculum.runInstructions?.vscode?.steps?.map((tip, idx) => (
                                        <li key={idx} className="flex gap-4 text-zinc-300 bg-zinc-900/50 p-4 rounded-xl border border-white/5">
                                            <div className="w-6 h-6 rounded-full bg-blue-500/20 flex items-center justify-center text-blue-400 text-xs font-bold shrink-0">
                                                {idx + 1}
                                            </div>
                                            <span className="text-sm leading-relaxed">{tip}</span>
                                        </li>
                                    ))}
                                    {(!curriculum.runInstructions?.vscode?.steps || curriculum.runInstructions.vscode.steps.length === 0) && (
                                        <div className="text-zinc-500 italic text-sm">Load the folder into VS Code and execute.</div>
                                    )}
                                </ul>
                            </div>

                        </div>
                    </Card>
                </div>

            </div>
        </div>
    )
}
